import type { Metadata } from 'next';
import { Golos_Text } from 'next/font/google';
import './globals.css';
import { NavBar } from '@/components/NavBar';
import { ThemeProvider } from '@/components/ThemeProvider';
import { AuthProvider } from '@/lib/AuthContext';

const golosText = Golos_Text({
  variable: '--font-golos-text',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    template: 'cardie.net | %s',
    default: 'cardie.net',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${golosText.variable} ${golosText.className}`}
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="default"
          enableSystem={false}
          themes={['default', 'purple-pink', 'black-white', 'pink-white']}
        >
          <AuthProvider>
            <NavBar />
            {children}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
